level:
  format: "(g*500)+1500"
  max: 1000
currency:
  money-name: "铜币"
  point-name: "钻币"
  auto-money: 0
  auto-point: 0
  pointTomoney: 10
prefix:
  OP: "管理员"
  PLAYER: "玩家"
  nick-switch: true
  prefix-switch: true
  chat-switch: true
  tag-switch: true
  #pre - 称号
  #name - 玩家名称
  #grade - 等级
  #per - 玩家权限: OP或玩家
  format: "[@pre]@name"

  #format - 名称显示格式
  #msg - 聊天信息
  chat-format: "@format: @msg"